# Generated by Django 4.2.28 on 2026-02-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_remove_employee_created_at_alter_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
